### ISSUE TITLE
setup/oe_get_seal_key_enc_fuzz - AddressSanitizer: 16384 byte(s) leaked in 1 allocation(s).

### ISSUE THREAD

**Issue by mrragava** [openenclave/openenclave-security#11]
## Files

* input: [leak-df71925a9099789036d7d894713adb14278a70d0](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-crashes-0bbc026a988a5b92a72b5b731e8eaf5c&filename=leak-df71925a9099789036d7d894713adb14278a70d0)
* exe: [setup/oe_get_seal_key_enc_fuzz]( https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-setup-81008742496b548388be60418a7ce4cd&filename=oe_get_seal_key_enc_fuzz)
* report: [c0ed100ea8cf4fb015051ed35527985ddd98c1b3aa953d84b22333b88a0147d8.json](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-unique-reports-0bbc026a988a5b92a72b5b731e8eaf5c&filename=c0ed100ea8cf4fb015051ed35527985ddd98c1b3aa953d84b22333b88a0147d8.json)

## Repro

 `onefuzz --endpoint https://openenclaveonefuzz223instance.azurewebsites.net repro create_and_connect oft-unique-reports-0bbc026a988a5b92a72b5b731e8eaf5c c0ed100ea8cf4fb015051ed35527985ddd98c1b3aa953d84b22333b88a0147d8.json`

## Call Stack

```#0 0x5507d3 in malloc /home/oe-llvm/compiler-rt/lib/asan/asan_malloc_linux.cc:146:3
#1 0x8328fb in _setup_ecall_context /__w/openenclave-security/openenclave-security/sut/openenclave/host/sgx/enter.c:143:33
#2 0x8328fb in __morestack /__w/openenclave-security/openenclave-security/sut/openenclave/host/sgx/enter.c:189
#3 0x822c40 in _do_eenter /__w/openenclave-security/openenclave-security/sut/openenclave/host/sgx/calls.c:193:13
#4 0x822c40 in oe_ecall /__w/openenclave-security/openenclave-security/sut/openenclave/host/sgx/calls.c:612
#5 0x658c9d in _initialize_enclave /__w/openenclave-security/openenclave-security/sut/openenclave/host/sgx/create.c:464:5
#6 0x6569f9 in oe_create_enclave /__w/openenclave-security/openenclave-security/sut/openenclave/host/sgx/create.c:1190:5
#7 0x59e405 in oe_create_enclaveapis_enclave /__w/openenclave-security/openenclave-security/build/fuzzing_build/src/dynamic/fuzzing/enclaveapis/host/enclaveapis_u.c:4384:12
#8 0x58190b in enclaveapi_fuzzer::enclaveapi_fuzzer() /__w/openenclave-security/openenclave-security/src/dynamic/fuzzing/enclaveapis/host/host.cpp:72:30
#9 0x580fb1 in std::_MakeUniq<enclaveapi_fuzzer>::__single_object std::make_unique<enclaveapi_fuzzer>() /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/unique_ptr.h:821:34
#10 0x580cb5 in LLVMFuzzerTestOneInput /__w/openenclave-security/openenclave-security/src/dynamic/fuzzing/enclaveapis/host/host.cpp:113:50
#11 0x45824a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /home/oe-llvm/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:533:15
#12 0x44c951 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /home/oe-llvm/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:280:6
#13 0x4513eb in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /home/oe-llvm/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:709:9
#14 0x476482 in main /home/oe-llvm/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
#15 0x7ffff65cebf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
```

## ASAN Log

```INFO: Seed: 1314594225
INFO: Loaded 1 modules   (20397 guards): 20397 [0xad6580, 0xaea434), 
setup/oe_get_seal_key_enc_fuzz: Running 1 inputs 1 time(s) each.
Running: /onefuzz/d31580c1-7efd-4d84-97cf-732a4a357bf7/task_crashes_1/leak-df71925a9099789036d7d894713adb14278a70d0
[enclave_create sgx_enclave_common.cpp:365] 
 secs->attibutes.flags = 6, secs->attributes.xfrm = 7 
[enclave_create sgx_enclave_common.cpp:365] 
 secs->attibutes.flags = 6, secs->attributes.xfrm = 7 

=================================================================
==11137==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16384 byte(s) in 1 object(s) allocated from:
    #0 0x5507d3 in malloc /home/oe-llvm/compiler-rt/lib/asan/asan_malloc_linux.cc:146:3
    #1 0x8328fb in _setup_ecall_context /__w/openenclave-security/openenclave-security/sut/openenclave/host/sgx/enter.c:143:33
    #2 0x8328fb in __morestack /__w/openenclave-security/openenclave-security/sut/openenclave/host/sgx/enter.c:189
    #3 0x822c40 in _do_eenter /__w/openenclave-security/openenclave-security/sut/openenclave/host/sgx/calls.c:193:13
    #4 0x822c40 in oe_ecall /__w/openenclave-security/openenclave-security/sut/openenclave/host/sgx/calls.c:612
    #5 0x658c9d in _initialize_enclave /__w/openenclave-security/openenclave-security/sut/openenclave/host/sgx/create.c:464:5
    #6 0x6569f9 in oe_create_enclave /__w/openenclave-security/openenclave-security/sut/openenclave/host/sgx/create.c:1190:5
    #7 0x59e405 in oe_create_enclaveapis_enclave /__w/openenclave-security/openenclave-security/build/fuzzing_build/src/dynamic/fuzzing/enclaveapis/host/enclaveapis_u.c:4384:12
    #8 0x58190b in enclaveapi_fuzzer::enclaveapi_fuzzer() /__w/openenclave-security/openenclave-security/src/dynamic/fuzzing/enclaveapis/host/host.cpp:72:30
    #9 0x580fb1 in std::_MakeUniq<enclaveapi_fuzzer>::__single_object std::make_unique<enclaveapi_fuzzer>() /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/unique_ptr.h:821:34
    #10 0x580cb5 in LLVMFuzzerTestOneInput /__w/openenclave-security/openenclave-security/src/dynamic/fuzzing/enclaveapis/host/host.cpp:113:50
    #11 0x45824a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /home/oe-llvm/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:533:15
    #12 0x44c951 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /home/oe-llvm/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:280:6
    #13 0x4513eb in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /home/oe-llvm/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:709:9
    #14 0x476482 in main /home/oe-llvm/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #15 0x7ffff65cebf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310

SUMMARY: AddressSanitizer: 16384 byte(s) leaked in 1 allocation(s).

INFO: a leak has been found in the initial corpus.

INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.

```

**Comment by mrragava** [comment]
Duplicate found.

* input: [leak-df71925a9099789036d7d894713adb14278a70d0](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-crashes-0bbc026a988a5b92a72b5b731e8eaf5c&filename=leak-df71925a9099789036d7d894713adb14278a70d0)
* exe: [setup/oe_get_seal_key_enc_fuzz]( https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-setup-81008742496b548388be60418a7ce4cd&filename=oe_get_seal_key_enc_fuzz)
* report: [c0ed100ea8cf4fb015051ed35527985ddd98c1b3aa953d84b22333b88a0147d8.json](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-unique-reports-0bbc026a988a5b92a72b5b731e8eaf5c&filename=c0ed100ea8cf4fb015051ed35527985ddd98c1b3aa953d84b22333b88a0147d8.json)

**Comment by mrragava** [comment]
Duplicate found.

* input: [leak-df71925a9099789036d7d894713adb14278a70d0](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-crashes-0bbc026a988a5b92a72b5b731e8eaf5c&filename=leak-df71925a9099789036d7d894713adb14278a70d0)
* exe: [setup/oe_get_seal_key_enc_fuzz]( https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-setup-81008742496b548388be60418a7ce4cd&filename=oe_get_seal_key_enc_fuzz)
* report: [c0ed100ea8cf4fb015051ed35527985ddd98c1b3aa953d84b22333b88a0147d8.json](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-unique-reports-0bbc026a988a5b92a72b5b731e8eaf5c&filename=c0ed100ea8cf4fb015051ed35527985ddd98c1b3aa953d84b22333b88a0147d8.json)

**Comment by mrragava** [comment]
Duplicate found.

* input: [leak-df71925a9099789036d7d894713adb14278a70d0](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-crashes-0bbc026a988a5b92a72b5b731e8eaf5c&filename=leak-df71925a9099789036d7d894713adb14278a70d0)
* exe: [setup/oe_get_seal_key_enc_fuzz]( https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-setup-81008742496b548388be60418a7ce4cd&filename=oe_get_seal_key_enc_fuzz)
* report: [c0ed100ea8cf4fb015051ed35527985ddd98c1b3aa953d84b22333b88a0147d8.json](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-unique-reports-0bbc026a988a5b92a72b5b731e8eaf5c&filename=c0ed100ea8cf4fb015051ed35527985ddd98c1b3aa953d84b22333b88a0147d8.json)

**Comment by mrragava** [comment]
Duplicate found.

* input: [leak-df71925a9099789036d7d894713adb14278a70d0](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-crashes-0bbc026a988a5b92a72b5b731e8eaf5c&filename=leak-df71925a9099789036d7d894713adb14278a70d0)
* exe: [setup/oe_get_seal_key_enc_fuzz]( https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-setup-81008742496b548388be60418a7ce4cd&filename=oe_get_seal_key_enc_fuzz)
* report: [c0ed100ea8cf4fb015051ed35527985ddd98c1b3aa953d84b22333b88a0147d8.json](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-unique-reports-0bbc026a988a5b92a72b5b731e8eaf5c&filename=c0ed100ea8cf4fb015051ed35527985ddd98c1b3aa953d84b22333b88a0147d8.json)

**Comment by mrragava** [comment]
Fixed in https://github.com/openenclave/openenclave/pull/4055
