### ISSUE TITLE
setup/oe_generate_attestation_certificate_enc_fuzz - AddressSanitizer: 2019 byte(s) leaked in 40 allocation(s).

### ISSUE THREAD

**Issue by mrragava** [openenclave/openenclave-security#17]
## Files

* input: [leak-232816e91259106d0c0a2f04c231f7878419e9a6](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-crashes-6381ca8c06085591b165ab940ac360ba&filename=leak-232816e91259106d0c0a2f04c231f7878419e9a6)
* exe: [setup/oe_generate_attestation_certificate_enc_fuzz]( https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-setup-cb6777735cc453f99c74f69eb5ec078c&filename=oe_generate_attestation_certificate_enc_fuzz)
* report: [2143f88e2bef5fdaf00478980a4ed6a2beef7cdd91d266d35779089031ac0a8c.json](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-unique-reports-6381ca8c06085591b165ab940ac360ba&filename=2143f88e2bef5fdaf00478980a4ed6a2beef7cdd91d266d35779089031ac0a8c.json)

## Repro

 `onefuzz --endpoint https://openenclaveonefuzz223instance.azurewebsites.net repro create_and_connect oft-unique-reports-6381ca8c06085591b165ab940ac360ba 2143f88e2bef5fdaf00478980a4ed6a2beef7cdd91d266d35779089031ac0a8c.json`

## Call Stack

```#0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
```

## ASAN Log

```INFO: Seed: 1819515947
INFO: Loaded 1 modules   (21072 guards): 21072 [0xaf81a0, 0xb0cae0), 
setup/oe_generate_attestation_certificate_enc_fuzz: Running 1 inputs 1 time(s) each.
Running: /onefuzz/9f506e33-79f0-4cdd-8cc4-7d34b48cf783/task_crashes_1/leak-232816e91259106d0c0a2f04c231f7878419e9a6
[enclave_create sgx_enclave_common.cpp:365] 
 secs->attibutes.flags = 6, secs->attributes.xfrm = 7 
[enclave_create sgx_enclave_common.cpp:365] 
 secs->attibutes.flags = 6, secs->attributes.xfrm = 7 
Executed /onefuzz/9f506e33-79f0-4cdd-8cc4-7d34b48cf783/task_crashes_1/leak-232816e91259106d0c0a2f04c231f7878419e9a6 in 4381 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***

=================================================================
==11267==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 168 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39e93  (<unknown module>)

Direct leak of 160 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39c84  (<unknown module>)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a21799  (<unknown module>)

Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39cc2  (<unknown module>)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a3a007  (<unknown module>)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39ce1  (<unknown module>)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39e36  (<unknown module>)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39d00  (<unknown module>)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39ed1  (<unknown module>)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a3a045  (<unknown module>)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39eb2  (<unknown module>)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39dd9  (<unknown module>)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39d1f  (<unknown module>)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39df8  (<unknown module>)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39e17  (<unknown module>)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39fe8  (<unknown module>)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a3a0a4  (<unknown module>)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39dba  (<unknown module>)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39f6c  (<unknown module>)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39f2e  (<unknown module>)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39f0f  (<unknown module>)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39ef0  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39e74  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39e55  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39d3e  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a3a084  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a3a064  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a3a026  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39ca3  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39fc9  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39faa  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39f8b  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39d9b  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39f4d  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39d7c  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a39d5d  (<unknown module>)

Indirect leak of 27 byte(s) in 1 object(s) allocated from:
    #0 0x57de92 in operator new[](unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:109:3
    #1 0x7ffff3a27a27  (<unknown module>)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a21721  (<unknown module>)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a216fb  (<unknown module>)

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x57dd02 in operator new(unsigned long) /home/oe-llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7ffff3a216df  (<unknown module>)

SUMMARY: AddressSanitizer: 2019 byte(s) leaked in 40 allocation(s).
```

**Comment by mrragava** [comment]
Duplicate found.

* input: [leak-232816e91259106d0c0a2f04c231f7878419e9a6](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-crashes-6381ca8c06085591b165ab940ac360ba&filename=leak-232816e91259106d0c0a2f04c231f7878419e9a6)
* exe: [setup/oe_generate_attestation_certificate_enc_fuzz]( https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-setup-cb6777735cc453f99c74f69eb5ec078c&filename=oe_generate_attestation_certificate_enc_fuzz)
* report: [2143f88e2bef5fdaf00478980a4ed6a2beef7cdd91d266d35779089031ac0a8c.json](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-unique-reports-6381ca8c06085591b165ab940ac360ba&filename=2143f88e2bef5fdaf00478980a4ed6a2beef7cdd91d266d35779089031ac0a8c.json)

**Comment by mrragava** [comment]
Duplicate found.

* input: [leak-232816e91259106d0c0a2f04c231f7878419e9a6](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-crashes-6381ca8c06085591b165ab940ac360ba&filename=leak-232816e91259106d0c0a2f04c231f7878419e9a6)
* exe: [setup/oe_generate_attestation_certificate_enc_fuzz]( https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-setup-cb6777735cc453f99c74f69eb5ec078c&filename=oe_generate_attestation_certificate_enc_fuzz)
* report: [2143f88e2bef5fdaf00478980a4ed6a2beef7cdd91d266d35779089031ac0a8c.json](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-unique-reports-6381ca8c06085591b165ab940ac360ba&filename=2143f88e2bef5fdaf00478980a4ed6a2beef7cdd91d266d35779089031ac0a8c.json)

**Comment by mrragava** [comment]
Duplicate found.

* input: [leak-232816e91259106d0c0a2f04c231f7878419e9a6](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-crashes-6381ca8c06085591b165ab940ac360ba&filename=leak-232816e91259106d0c0a2f04c231f7878419e9a6)
* exe: [setup/oe_generate_attestation_certificate_enc_fuzz]( https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-setup-cb6777735cc453f99c74f69eb5ec078c&filename=oe_generate_attestation_certificate_enc_fuzz)
* report: [2143f88e2bef5fdaf00478980a4ed6a2beef7cdd91d266d35779089031ac0a8c.json](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-unique-reports-6381ca8c06085591b165ab940ac360ba&filename=2143f88e2bef5fdaf00478980a4ed6a2beef7cdd91d266d35779089031ac0a8c.json)

**Comment by mrragava** [comment]
Duplicate found.

* input: [leak-232816e91259106d0c0a2f04c231f7878419e9a6](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-crashes-6381ca8c06085591b165ab940ac360ba&filename=leak-232816e91259106d0c0a2f04c231f7878419e9a6)
* exe: [setup/oe_generate_attestation_certificate_enc_fuzz]( https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-setup-cb6777735cc453f99c74f69eb5ec078c&filename=oe_generate_attestation_certificate_enc_fuzz)
* report: [2143f88e2bef5fdaf00478980a4ed6a2beef7cdd91d266d35779089031ac0a8c.json](https://openenclaveonefuzz223instance.azurewebsites.net/api/download?container=oft-unique-reports-6381ca8c06085591b165ab940ac360ba&filename=2143f88e2bef5fdaf00478980a4ed6a2beef7cdd91d266d35779089031ac0a8c.json)
